version: '3.3'

services:
  sync_worker:
    build: .
    restart: on-failure
    env_file:
      - .env
    container_name: sync_worker
    networks:
      ai_chat-backend:

networks:
  ai_chat-backend:
